version: '3'
services:
  php-server:
    build:
      context: ./docker 
      dockerfile: Dockerfile
    image: php-custom-server 
    volumes:
      - ./project:/var/www/html/
    ports:
      - "80:80"
    links:
      - db
  db:
    image: mysql:5.6
    ports:
      - "3306:3306"
    
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_DATABASE=desenvolvimento
    volumes:
      - ./docker/mysql_volume:/var/lib/mysql
